-- +goose Up
-- If users.id isn't identity yet, convert it. For fresh demo DBs you can instead recreate users table.
-- This assumes users.id is BIGINT and currently NOT identity.
ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- +goose Down
ALTER TABLE users ALTER COLUMN id DROP IDENTITY IF EXISTS;
