// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package users

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/edlingao/hexago/web/templates"

type ChoosePlanVM struct{ Error error }

func ChoosePlan(vm ChoosePlanVM) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<link href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap\" rel=\"stylesheet\"><div class=\"min-h-screen bg-slate-100\" x-data=\"choosePlanStore()\" x-init=\"init()\">(\"choose-plan\")<main class=\"max-w-5xl mx-auto px-4 py-10\"><h1 class=\"text-3xl font-black text-slate-800\">Choose your plan</h1><p class=\"text-slate-500 mt-2\">Pick a subscription to activate your account.</p><div x-show=\"error\" x-cloak class=\"mt-6 p-4 bg-red-50 border border-red-200 text-red-700 rounded-lg\" x-text=\"error\"></div><div class=\"grid grid-cols-1 md:grid-cols-3 gap-6 mt-8\"><template x-for=\"p in plans\" :key=\"p.id\"><div class=\"bg-white rounded-xl border border-slate-200 shadow-sm p-6 flex flex-col\"><h3 class=\"text-xl font-bold text-slate-800\" x-text=\"p.name\"></h3><p class=\"text-slate-500 mt-1\" x-text=\"formatPrice(p.priceCents)\"></p><ul class=\"mt-4 space-y-2 text-sm text-slate-600\"><template x-for=\"f in p.features\" :key=\"f\"><li class=\"flex items-start gap-2\"><span class=\"material-symbols-outlined text-green-600 text-base\">check</span> <span x-text=\"f\"></span></li></template></ul><button class=\"mt-6 h-11 rounded-lg bg-blue-600 text-white font-bold hover:bg-blue-700 disabled:opacity-60\" @click=\"selectPlan(p.id)\" :disabled=\"loading\"><span x-text=\"loading ? 'Activating…' : 'Choose Plan'\"></span></button></div></template></div><div class=\"mt-10 flex items-center justify-between\"><div class=\"text-slate-500 text-sm\">Selected: <span class=\"font-semibold text-slate-800\" x-text=\"selectedPlan?.name || '—'\"></span></div><button class=\"px-5 py-3 rounded-lg bg-blue-600 text-white font-bold hover:bg-blue-700 disabled:opacity-50\" :disabled=\"saving || !selectedPlanId\" @click=\"save()\"><span x-text=\"saving ? 'Saving…' : 'Continue'\"></span></button></div></main></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = templates.Index(templates.IndexVM{Title: "Choose Plan - Hedgestone Carwash", Error: vm.Error}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
