// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package users

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func DashboardHeader(active string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header class=\"bg-white border-b border-slate-200 -mx-4 sm:-mx-6 lg:-mx-8 pl-4 pr-0 sm:px-6 lg:px-8\" x-data=\"{ open: false }\"><div class=\"flex h-24 items-center justify-between\"><a href=\"/dashboard\" class=\"flex items-center gap-3\"><img src=\"/static/logo.svg\" class=\"h-16 w-16 md:h-24 md:w-24 shrink-0\" alt=\"Hedgestone\"><div class=\"leading-tight\"><div class=\"text-sm text-slate-500 tracking-wide\">Hedgestone</div><div class=\"text-2xl font-semibold text-slate-900\">Carwash</div></div></a><nav class=\"hidden md:flex items-center gap-10 text-sm font-medium text-slate-600\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if active == "dashboard" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<a class=\"h-16 flex items-center border-b-2 border-amber-500 text-slate-900\" href=\"/dashboard\">Dashboard</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<a class=\"h-16 flex items-center border-b-2 border-transparent hover:text-slate-900\" href=\"/dashboard\">Dashboard</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if active == "history" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<a class=\"h-16 flex items-center border-b-2 border-amber-500 text-slate-900\" href=\"/history\">History</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<a class=\"h-16 flex items-center border-b-2 border-transparent hover:text-slate-900\" href=\"/history\">History</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if active == "account" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<a class=\"h-16 flex items-center border-b-2 border-amber-500 text-slate-900\" href=\"/account\">Account</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<a class=\"h-16 flex items-center border-b-2 border-transparent hover:text-slate-900\" href=\"/account\">Account</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<button @click=\"$store.auth && $store.auth.logout ? $store.auth.logout() : (window.location.href='/login')\" class=\"h-16 flex items-center border-b-2 border-transparent hover:text-red-600\">Logout</button></nav><div class=\"md:hidden -mr-6 relative\"><button @click=\"open=!open\" class=\"h-10 w-10 rounded-lg border border-slate-200 bg-white flex items-center justify-center -mr-4\"><span class=\"material-symbols-outlined text-slate-800\">menu</span></button><div x-show=\"open\" x-cloak x-transition @click.outside=\"open=false\" class=\"absolute right-0 mt-2 w-56 rounded-xl bg-white shadow-lg border border-slate-200 overflow-hidden z-50\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if active == "dashboard" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<a class=\"block px-4 py-3 bg-slate-50 text-slate-900 font-semibold\" href=\"/dashboard\">Dashboard</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<a class=\"block px-4 py-3 text-slate-700 hover:bg-slate-50\" href=\"/dashboard\">Dashboard</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if active == "history" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<a class=\"block px-4 py-3 bg-slate-50 text-slate-900 font-semibold\" href=\"/history\">History</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<a class=\"block px-4 py-3 text-slate-700 hover:bg-slate-50\" href=\"/history\">History</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if active == "account" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "<a class=\"block px-4 py-3 bg-slate-50 text-slate-900 font-semibold\" href=\"/account\">Account</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "<a class=\"block px-4 py-3 text-slate-700 hover:bg-slate-50\" href=\"/account\">Account</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "<button @click=\"$store.auth && $store.auth.logout ? $store.auth.logout() : (window.location.href='/login')\" class=\"w-full text-left block px-4 py-3 text-slate-700 hover:bg-slate-50\">Logout</button></div></div><div class=\"flex items-center gap-3\"></div></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
