// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package users

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func DashboardHeader(active string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header class=\"bg-white border-b border-slate-200 -mx-4 sm:-mx-6 lg:-mx-8 px-4 sm:px-6 lg:px-8\"><div class=\"flex h-16 items-center justify-between\"><a href=\"/dashboard\" class=\"flex items-center gap-3\"><img src=\"/static/logo.svg\" class=\"h-9 w-9\" alt=\"Hedgestone\"><div class=\"leading-tight\"><div class=\"text-xs text-slate-500 tracking-wide\">Hedgestone</div><div class=\"text-base font-semibold text-slate-900\">Carwash</div></div></a><nav class=\"hidden md:flex items-center gap-10 text-sm font-medium text-slate-600\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if active == "dashboard" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<a class=\"h-16 flex items-center border-b-2 border-amber-500 text-slate-900\" href=\"/dashboard\">Dashboard</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<a class=\"h-16 flex items-center border-b-2 border-transparent hover:text-slate-900\" href=\"/dashboard\">Dashboard</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if active == "history" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<a class=\"h-16 flex items-center border-b-2 border-amber-500 text-slate-900\" href=\"/history\">History</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<a class=\"h-16 flex items-center border-b-2 border-transparent hover:text-slate-900\" href=\"/history\">History</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if active == "account" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<a class=\"h-16 flex items-center border-b-2 border-amber-500 text-slate-900\" href=\"/account\">Account</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<a class=\"h-16 flex items-center border-b-2 border-transparent hover:text-slate-900\" href=\"/account\">Account</a> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<button @click=\"$store.auth && $store.auth.logout ? $store.auth.logout() : (window.location.href='/login')\" class=\"h-16 flex items-center border-b-2 border-transparent hover:text-red-600\">Logout</button></nav><div class=\"flex items-center gap-3\"><button class=\"h-10 w-10 rounded-full hover:bg-slate-100 flex items-center justify-center\" aria-label=\"Notifications\"><span class=\"material-symbols-outlined text-slate-700\">notifications</span></button> <a href=\"/account\" class=\"h-10 w-10 rounded-full bg-slate-200 flex items-center justify-center\" aria-label=\"Account\"><span class=\"material-symbols-outlined text-slate-700\">person</span></a></div></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
