// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/edlingao/hexago/web/templates"

type CookiesVM struct {
	Error error
}

func Cookies(vm CookiesVM) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"bg-base-200 min-h-screen\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = PublicNavbar().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"bg-white\"><div class=\"max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-16\"><h1 class=\"text-4xl font-extrabold text-gray-900\">Cookie Policy</h1><p class=\"mt-4 text-gray-600\">Last updated: January 9, 2026</p><div class=\"mt-10 space-y-8 text-gray-700 leading-relaxed\"><section><h2 class=\"text-2xl font-bold text-gray-900\">1. What are cookies?</h2><p class=\"mt-3\">Cookies are small text files stored on your device to help websites function and improve user experience.</p></section><section><h2 class=\"text-2xl font-bold text-gray-900\">2. How we use cookies</h2><ul class=\"mt-3 list-disc list-inside space-y-2\"><li>Essential cookies for authentication and session management.</li><li>Security cookies to detect abuse and protect accounts.</li><li>Preference cookies to remember basic settings (where applicable).</li></ul></section><section><h2 class=\"text-2xl font-bold text-gray-900\">3. Your choices</h2><p class=\"mt-3\">You can control cookies through your browser settings. Disabling cookies may impact functionality.</p></section><section><h2 class=\"text-2xl font-bold text-gray-900\">4. Contact</h2><p class=\"mt-3\">Questions can be sent via our <a class=\"text-blue-600 hover:underline\" href=\"/contact\">Contact</a> page.</p></section></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = PublicFooter().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = templates.Index(templates.IndexVM{Title: "Cookie Policy - Hedgestone Carwash", Error: vm.Error}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
